{% set name = "flake8-isort" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-isort-{{ version }}.tar.gz
  sha256: 9259cf60f63eb13014ba7aeef116f205d813302c2404f6e07aef1a3291d25cb8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - flake8
    - isort >=4.3.5,<6

test:
  imports:
    - flake8_isort
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/gforcada/flake8-isort
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: flake8 plugin that integrates isort .
  dev_url: https://github.com/gforcada/flake8-isort

extra:
  recipe-maintainers:
    - dopplershift
    - marcelotrevisani
    - xylar
