{% set name = "flake8-isort" %}
{% set version = "2.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 64454d1f154a303cfe23ee715aca37271d4f1d299b2f2663f45b73bff14e36a9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - flake8 >=3.2.1
    - isort >=4.3.0
    - python
    - testfixtures

test:
  imports:
    - flake8_isort

about:
  home: "https://github.com/gforcada/flake8-isort"
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: "flake8 plugin that integrates isort ."
  dev_url: https://github.com/gforcada/flake8-isort

extra:
  recipe-maintainers:
    - marcelotrevisani
